Fix spec
kbrw/sweet_xml pull request #98
Opened 2024-01-31 00:27 UTC by joaothallis

2024-03-14 15:06 UTC, half-shell requested changes
Hi @joaothallis :wave: 

Thank you for contributing to one of our repo! Sorry it took that long for one of us to review this.

I'll gladly merge this once you get around to implement the changes I suggested :slightly_smiling_face: 

Thanks again!

2024-03-14 15:06 UTC, half-shell commented on mix.exs
> +      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false}
We're not keen on having `dialyxir` as a dependency just yet.

We might in the future, it is just not something that we want to do in isolation, in this repo only.
We currently are in the process of cleaning up our repos, and decided that this kind of change would be discussed down the line.

We'll gladly add those later on if it is something we decide to do as an organization.

2024-03-14 15:06 UTC, half-shell commented on lib/sweet_xml.ex
> +  @spec xmap(parent :: (doc | xmlElement), mapping :: specs, options :: (boolean | map)) :: (map | keyword | nil)
Would you mind adding `nil` as an input option as well?

```suggestion
  @spec xmap(parent :: (doc | xmlElement | nil), mapping :: specs, options :: (boolean | map)) :: (map | keyword | nil)
```

2024-08-20 08:17 UTC, half-shell requested changes

2024-08-20 08:17 UTC, half-shell commented on mix.lock
> +  "dialyxir": {:hex, :dialyxir, "1.4.3", "edd0124f358f0b9e95bfe53a9fcf806d615d8f838e2202a9f430d59566b6b53b", [:mix], [{:erlex, ">= 0.2.6", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "b
It seems you forgot to commit the `mix.lock` file.

You can just amend it to your previous commit and I'll merge this :+1:

2026-02-26 19:47 UTC, joaothallis commented
I ran `mix dialyzer` in `master` and there's no warning anymore

2026-02-26 19:47 UTC, closed without merging